In [6]:
import numpy as np

In [7]:
myarr = np.array([1,2,3,4,5])

In [8]:
myarr

array([1, 2, 3, 4, 5])

#2D Arrays

In [2]:
import numpy as np
arr = np.array([[1,3,4], [5,6,7]])
print(arr)

[[1 3 4]
 [5 6 7]]


#3-D Arrays

In [5]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [1]:
print("Just pushing the code into git hub for streaks!")

Just pushing the code into git hub for streaks!


In [1]:
a = "hi"
b = "meow"
print(a + b)

himeow


In [1]:
print("Hello, this is me pratikshya")

Hello, this is me pratikshya
